// <auto-generated />
using System;
using DAL.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210426052917_Seed2")]
    partial class Seed2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<int>("MediaType");

                    b.Property<Guid>("TaskId");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("DAL.Models.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Key");

                    b.Property<string>("Name");

                    b.Property<string>("PhaseOrder");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.HasKey("Id");

                    b.ToTable("Board");
                });

            modelBuilder.Entity("DAL.Models.BoardUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BoardId");

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<int>("MemberType");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("UserId");

                    b.ToTable("BoardUser");
                });

            modelBuilder.Entity("DAL.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("TaskId");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("DAL.Models.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BoardId");

                    b.Property<string>("Color");

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.HasKey("Id");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("DAL.Models.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BoardId");

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<string>("Name");

                    b.Property<string>("TaskOrder");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Phase");
                });

            modelBuilder.Entity("DAL.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.HasKey("Id");

                    b.ToTable("Position");

                    b.HasData(
                        new
                        {
                            Id = new Guid("514b3faa-07bb-4c60-9f2e-f78fad36f0b1"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "Project Manager",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "HR",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "Dev",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "Tester",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "QA",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "Admin",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "User",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("DAL.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.HasKey("Id");

                    b.ToTable("Skill");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = ".NET Core",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "Java",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "Android",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "iOS",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "ReactJS",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "React Native",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "Flutter",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "Angular",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "VueJS",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "Ruby",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Name = "ModeJS",
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("DAL.Models.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BoardId");

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<string>("Description");

                    b.Property<DateTimeOffset>("DueDate");

                    b.Property<int>("EntityStatus");

                    b.Property<TimeSpan>("Estimation");

                    b.Property<Guid?>("ReporterId");

                    b.Property<Guid>("ReporterUserId");

                    b.Property<TimeSpan>("SpentTime");

                    b.Property<long>("TaskKey");

                    b.Property<string>("Title");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("DAL.Models.TaskAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionDescription");

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("TaskId");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAction");
                });

            modelBuilder.Entity("DAL.Models.TaskAssignee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("TaskId");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskAssignee");
                });

            modelBuilder.Entity("DAL.Models.TaskLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("LabelId");

                    b.Property<Guid>("TaskId");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.HasKey("Id");

                    b.HasIndex("LabelId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskLabel");
                });

            modelBuilder.Entity("DAL.Models.TimeLineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<string>("Event");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TimeLineEvent");
                });

            modelBuilder.Entity("DAL.Models.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<bool>("Finished");

                    b.Property<Guid>("TaskId");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Todo");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTimeOffset?>("AllowTokensSince");

                    b.Property<string>("AvatarUrl");

                    b.Property<DateTimeOffset>("BirthDate");

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<int>("EntityStatus");

                    b.Property<string>("FullName");

                    b.Property<int>("Gender");

                    b.Property<string>("Location");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired();

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired();

                    b.Property<string>("Phone");

                    b.Property<Guid>("PositionId");

                    b.Property<string>("SocialLink");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0e9aa05-db0c-41d1-97ba-243900bd18ba"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("514b3faa-07bb-4c60-9f2e-f78fad36f0b1"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "An Nguyen",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Van Truong",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Tu Chau",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Suong Tran",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Quy Tran",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Quy Nguyen",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Son Nguyen",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Tu Nguyen",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Tu Phan",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Tu Tran",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Anh Phan",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Anh Nguyen",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Tue Anh Nguyen",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Huyen Nguyen",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Kieu Bui",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Kieu Tran",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Mi Tran",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "My Nguyen",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Ha Nguyen",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Ha Tran",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Ha Phan",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Address = "80 Nguyen Chanh - Lien Chieu - Da Nang",
                            BirthDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            FullName = "Buu Dam",
                            Gender = 0,
                            PasswordHash = new byte[] { 95, 32, 72, 16, 82, 4, 40, 199, 74, 89, 63, 121, 6, 183, 232, 74, 217, 79, 42, 143, 35, 209, 67, 46, 227, 68, 153, 46, 143, 3, 66, 146 },
                            PasswordSalt = new byte[] { 113, 185, 201, 153, 102, 169, 39, 242, 205, 86, 24, 128, 188, 12, 116, 189, 46, 187, 141, 81, 26, 22, 166, 92, 146, 238, 56, 142, 85, 105, 228, 10, 156, 47, 91, 76, 33, 80, 228, 236, 170, 240, 169, 106, 75, 125, 66, 53, 77, 167, 225, 57, 177, 33, 209, 25, 205, 223, 1, 118, 31, 53, 121, 74 },
                            PositionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "damvanhoangbuu1"
                        });
                });

            modelBuilder.Entity("DAL.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("RoleId");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityStatus = 0,
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            UpdatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("c0e9aa05-db0c-41d1-97ba-243900bd18ba")
                        });
                });

            modelBuilder.Entity("DAL.Models.UserSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("SkillId");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkill");
                });

            modelBuilder.Entity("DAL.Models.WorkLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("Amount");

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<DateTimeOffset>("DateLog");

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("TaskId");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkLog");
                });

            modelBuilder.Entity("DAL.Models.Attachment", b =>
                {
                    b.HasOne("DAL.Models.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.BoardUser", b =>
                {
                    b.HasOne("DAL.Models.Board", "Board")
                        .WithMany("BoardUsers")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.Comment", b =>
                {
                    b.HasOne("DAL.Models.Task", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.Phase", b =>
                {
                    b.HasOne("DAL.Models.Board", "Board")
                        .WithMany("Phases")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.Task", b =>
                {
                    b.HasOne("DAL.Models.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.User", "Reporter")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("ReporterId");
                });

            modelBuilder.Entity("DAL.Models.TaskAction", b =>
                {
                    b.HasOne("DAL.Models.Task", "Task")
                        .WithMany("TaskActions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("TaskActions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.TaskAssignee", b =>
                {
                    b.HasOne("DAL.Models.Task", "Task")
                        .WithMany("TaskAssignees")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("TaskAssignees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.TaskLabel", b =>
                {
                    b.HasOne("DAL.Models.Label", "Label")
                        .WithMany("TaskLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Task", "Task")
                        .WithMany("TaskLabels")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.TimeLineEvent", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("TimeLineEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.Todo", b =>
                {
                    b.HasOne("DAL.Models.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.HasOne("DAL.Models.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.UserRole", b =>
                {
                    b.HasOne("DAL.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.UserSkill", b =>
                {
                    b.HasOne("DAL.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.WorkLog", b =>
                {
                    b.HasOne("DAL.Models.Task", "Task")
                        .WithMany("WorkLogs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("WorkLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
